### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by partiallywritten** [Itz-fork/Vrappy#1]
- [ ] Cleanup current UI
- [ ] Implement all the [listed features](https://github.com/Itz-fork/Vrappy#features) in CLI 
- [x] Support for local video files
- [ ] Support for selecting audio / subtitle track
- [ ] Caching system to reuse summarizations
- [ ] Support large audio files (> 25mb)
- [ ] Support for gpt vision
